// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RepliesColumns holds the columns for the "replies" table.
	RepliesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "message", Type: field.TypeString},
		{Name: "ats", Type: field.TypeString},
		{Name: "ip", Type: field.TypeInt64},
		{Name: "plat", Type: field.TypeInt8},
		{Name: "device", Type: field.TypeString},
		{Name: "version", Type: field.TypeString},
		{Name: "ctime", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "mtime", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "topics", Type: field.TypeString},
		{Name: "addr", Type: field.TypeString},
	}
	// RepliesTable holds the schema information for the "replies" table.
	RepliesTable = &schema.Table{
		Name:       "replies",
		Columns:    RepliesColumns,
		PrimaryKey: []*schema.Column{RepliesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RepliesTable,
	}
)

func init() {
}
