// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: api/commentService/v1/commentService.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCommentServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateCommentServiceRequest) Reset() {
	*x = CreateCommentServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentServiceRequest) ProtoMessage() {}

func (x *CreateCommentServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{0}
}

type CreateCommentServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateCommentServiceReply) Reset() {
	*x = CreateCommentServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentServiceReply) ProtoMessage() {}

func (x *CreateCommentServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentServiceReply.ProtoReflect.Descriptor instead.
func (*CreateCommentServiceReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{1}
}

type UpdateCommentServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCommentServiceRequest) Reset() {
	*x = UpdateCommentServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCommentServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentServiceRequest) ProtoMessage() {}

func (x *UpdateCommentServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{2}
}

type UpdateCommentServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCommentServiceReply) Reset() {
	*x = UpdateCommentServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCommentServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentServiceReply) ProtoMessage() {}

func (x *UpdateCommentServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentServiceReply.ProtoReflect.Descriptor instead.
func (*UpdateCommentServiceReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{3}
}

type DeleteCommentServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCommentServiceRequest) Reset() {
	*x = DeleteCommentServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentServiceRequest) ProtoMessage() {}

func (x *DeleteCommentServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{4}
}

type DeleteCommentServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCommentServiceReply) Reset() {
	*x = DeleteCommentServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentServiceReply) ProtoMessage() {}

func (x *DeleteCommentServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentServiceReply.ProtoReflect.Descriptor instead.
func (*DeleteCommentServiceReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{5}
}

type GetCommentServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCommentServiceRequest) Reset() {
	*x = GetCommentServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentServiceRequest) ProtoMessage() {}

func (x *GetCommentServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentServiceRequest.ProtoReflect.Descriptor instead.
func (*GetCommentServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{6}
}

type GetCommentServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCommentServiceReply) Reset() {
	*x = GetCommentServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentServiceReply) ProtoMessage() {}

func (x *GetCommentServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentServiceReply.ProtoReflect.Descriptor instead.
func (*GetCommentServiceReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{7}
}

type ListCommentServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCommentServiceRequest) Reset() {
	*x = ListCommentServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommentServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentServiceRequest) ProtoMessage() {}

func (x *ListCommentServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentServiceRequest.ProtoReflect.Descriptor instead.
func (*ListCommentServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{8}
}

type ListCommentServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCommentServiceReply) Reset() {
	*x = ListCommentServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommentServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentServiceReply) ProtoMessage() {}

func (x *ListCommentServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentServiceReply.ProtoReflect.Descriptor instead.
func (*ListCommentServiceReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{9}
}

var File_api_commentService_v1_commentService_proto protoreflect.FileDescriptor

var file_api_commentService_v1_commentService_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1d, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1b, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x0a, 0x1b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b,
	0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x81, 0x05, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7e, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x7e, 0x0a, 0x14, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x7e, 0x0a, 0x14, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x75, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x78, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x40, 0x0a, 0x15, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x25, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x6d,
	0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_commentService_v1_commentService_proto_rawDescOnce sync.Once
	file_api_commentService_v1_commentService_proto_rawDescData = file_api_commentService_v1_commentService_proto_rawDesc
)

func file_api_commentService_v1_commentService_proto_rawDescGZIP() []byte {
	file_api_commentService_v1_commentService_proto_rawDescOnce.Do(func() {
		file_api_commentService_v1_commentService_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_commentService_v1_commentService_proto_rawDescData)
	})
	return file_api_commentService_v1_commentService_proto_rawDescData
}

var file_api_commentService_v1_commentService_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_commentService_v1_commentService_proto_goTypes = []interface{}{
	(*CreateCommentServiceRequest)(nil), // 0: api.comment.service.v1.CreateCommentServiceRequest
	(*CreateCommentServiceReply)(nil),   // 1: api.comment.service.v1.CreateCommentServiceReply
	(*UpdateCommentServiceRequest)(nil), // 2: api.comment.service.v1.UpdateCommentServiceRequest
	(*UpdateCommentServiceReply)(nil),   // 3: api.comment.service.v1.UpdateCommentServiceReply
	(*DeleteCommentServiceRequest)(nil), // 4: api.comment.service.v1.DeleteCommentServiceRequest
	(*DeleteCommentServiceReply)(nil),   // 5: api.comment.service.v1.DeleteCommentServiceReply
	(*GetCommentServiceRequest)(nil),    // 6: api.comment.service.v1.GetCommentServiceRequest
	(*GetCommentServiceReply)(nil),      // 7: api.comment.service.v1.GetCommentServiceReply
	(*ListCommentServiceRequest)(nil),   // 8: api.comment.service.v1.ListCommentServiceRequest
	(*ListCommentServiceReply)(nil),     // 9: api.comment.service.v1.ListCommentServiceReply
}
var file_api_commentService_v1_commentService_proto_depIdxs = []int32{
	0, // 0: api.comment.service.v1.CommentService.CreateCommentService:input_type -> api.comment.service.v1.CreateCommentServiceRequest
	2, // 1: api.comment.service.v1.CommentService.UpdateCommentService:input_type -> api.comment.service.v1.UpdateCommentServiceRequest
	4, // 2: api.comment.service.v1.CommentService.DeleteCommentService:input_type -> api.comment.service.v1.DeleteCommentServiceRequest
	6, // 3: api.comment.service.v1.CommentService.GetCommentService:input_type -> api.comment.service.v1.GetCommentServiceRequest
	8, // 4: api.comment.service.v1.CommentService.ListCommentService:input_type -> api.comment.service.v1.ListCommentServiceRequest
	1, // 5: api.comment.service.v1.CommentService.CreateCommentService:output_type -> api.comment.service.v1.CreateCommentServiceReply
	3, // 6: api.comment.service.v1.CommentService.UpdateCommentService:output_type -> api.comment.service.v1.UpdateCommentServiceReply
	5, // 7: api.comment.service.v1.CommentService.DeleteCommentService:output_type -> api.comment.service.v1.DeleteCommentServiceReply
	7, // 8: api.comment.service.v1.CommentService.GetCommentService:output_type -> api.comment.service.v1.GetCommentServiceReply
	9, // 9: api.comment.service.v1.CommentService.ListCommentService:output_type -> api.comment.service.v1.ListCommentServiceReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_commentService_v1_commentService_proto_init() }
func file_api_commentService_v1_commentService_proto_init() {
	if File_api_commentService_v1_commentService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_commentService_v1_commentService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCommentServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCommentServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommentServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommentServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_commentService_v1_commentService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_commentService_v1_commentService_proto_goTypes,
		DependencyIndexes: file_api_commentService_v1_commentService_proto_depIdxs,
		MessageInfos:      file_api_commentService_v1_commentService_proto_msgTypes,
	}.Build()
	File_api_commentService_v1_commentService_proto = out.File
	file_api_commentService_v1_commentService_proto_rawDesc = nil
	file_api_commentService_v1_commentService_proto_goTypes = nil
	file_api_commentService_v1_commentService_proto_depIdxs = nil
}
