// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: api/commentService/v1/commentService.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateReplyRequest) Reset() {
	*x = CreateReplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyRequest) ProtoMessage() {}

func (x *CreateReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyRequest.ProtoReflect.Descriptor instead.
func (*CreateReplyRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{0}
}

type CreateReplyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateReplyReply) Reset() {
	*x = CreateReplyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyReply) ProtoMessage() {}

func (x *CreateReplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyReply.ProtoReflect.Descriptor instead.
func (*CreateReplyReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{1}
}

type UpdateReplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReplyRequest) Reset() {
	*x = UpdateReplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplyRequest) ProtoMessage() {}

func (x *UpdateReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplyRequest.ProtoReflect.Descriptor instead.
func (*UpdateReplyRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{2}
}

type UpdateReplyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReplyReply) Reset() {
	*x = UpdateReplyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplyReply) ProtoMessage() {}

func (x *UpdateReplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplyReply.ProtoReflect.Descriptor instead.
func (*UpdateReplyReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{3}
}

type DeleteReplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReplyRequest) Reset() {
	*x = DeleteReplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyRequest) ProtoMessage() {}

func (x *DeleteReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyRequest.ProtoReflect.Descriptor instead.
func (*DeleteReplyRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{4}
}

type DeleteReplyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReplyReply) Reset() {
	*x = DeleteReplyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyReply) ProtoMessage() {}

func (x *DeleteReplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyReply.ProtoReflect.Descriptor instead.
func (*DeleteReplyReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{5}
}

type GetReplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReplyRequest) Reset() {
	*x = GetReplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyRequest) ProtoMessage() {}

func (x *GetReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyRequest.ProtoReflect.Descriptor instead.
func (*GetReplyRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{6}
}

type GetReplyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReplyReply) Reset() {
	*x = GetReplyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyReply) ProtoMessage() {}

func (x *GetReplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyReply.ProtoReflect.Descriptor instead.
func (*GetReplyReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{7}
}

type ListReplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListReplyRequest) Reset() {
	*x = ListReplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplyRequest) ProtoMessage() {}

func (x *ListReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplyRequest.ProtoReflect.Descriptor instead.
func (*ListReplyRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{8}
}

type ListReplyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListReplyReply) Reset() {
	*x = ListReplyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplyReply) ProtoMessage() {}

func (x *ListReplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplyReply.ProtoReflect.Descriptor instead.
func (*ListReplyReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{9}
}

type CreateReplyIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateReplyIndexRequest) Reset() {
	*x = CreateReplyIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReplyIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyIndexRequest) ProtoMessage() {}

func (x *CreateReplyIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyIndexRequest.ProtoReflect.Descriptor instead.
func (*CreateReplyIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{10}
}

type CreateReplyIndexReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateReplyIndexReply) Reset() {
	*x = CreateReplyIndexReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReplyIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyIndexReply) ProtoMessage() {}

func (x *CreateReplyIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyIndexReply.ProtoReflect.Descriptor instead.
func (*CreateReplyIndexReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{11}
}

type UpdateReplyIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReplyIndexRequest) Reset() {
	*x = UpdateReplyIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReplyIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplyIndexRequest) ProtoMessage() {}

func (x *UpdateReplyIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplyIndexRequest.ProtoReflect.Descriptor instead.
func (*UpdateReplyIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{12}
}

type UpdateReplyIndexReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReplyIndexReply) Reset() {
	*x = UpdateReplyIndexReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReplyIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplyIndexReply) ProtoMessage() {}

func (x *UpdateReplyIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplyIndexReply.ProtoReflect.Descriptor instead.
func (*UpdateReplyIndexReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{13}
}

type DeleteReplyIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReplyIndexRequest) Reset() {
	*x = DeleteReplyIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReplyIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyIndexRequest) ProtoMessage() {}

func (x *DeleteReplyIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyIndexRequest.ProtoReflect.Descriptor instead.
func (*DeleteReplyIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{14}
}

type DeleteReplyIndexReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReplyIndexReply) Reset() {
	*x = DeleteReplyIndexReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReplyIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyIndexReply) ProtoMessage() {}

func (x *DeleteReplyIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyIndexReply.ProtoReflect.Descriptor instead.
func (*DeleteReplyIndexReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{15}
}

type GetReplyIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReplyIndexRequest) Reset() {
	*x = GetReplyIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplyIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyIndexRequest) ProtoMessage() {}

func (x *GetReplyIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyIndexRequest.ProtoReflect.Descriptor instead.
func (*GetReplyIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{16}
}

type GetReplyIndexReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReplyIndexReply) Reset() {
	*x = GetReplyIndexReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplyIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyIndexReply) ProtoMessage() {}

func (x *GetReplyIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyIndexReply.ProtoReflect.Descriptor instead.
func (*GetReplyIndexReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{17}
}

type ListReplyIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListReplyIndexRequest) Reset() {
	*x = ListReplyIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReplyIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplyIndexRequest) ProtoMessage() {}

func (x *ListReplyIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplyIndexRequest.ProtoReflect.Descriptor instead.
func (*ListReplyIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{18}
}

type ListReplyIndexReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListReplyIndexReply) Reset() {
	*x = ListReplyIndexReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReplyIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplyIndexReply) ProtoMessage() {}

func (x *ListReplyIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplyIndexReply.ProtoReflect.Descriptor instead.
func (*ListReplyIndexReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{19}
}

type CreateReplyAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateReplyAreaRequest) Reset() {
	*x = CreateReplyAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReplyAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyAreaRequest) ProtoMessage() {}

func (x *CreateReplyAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyAreaRequest.ProtoReflect.Descriptor instead.
func (*CreateReplyAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{20}
}

type CreateReplyAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateReplyAreaReply) Reset() {
	*x = CreateReplyAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReplyAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyAreaReply) ProtoMessage() {}

func (x *CreateReplyAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyAreaReply.ProtoReflect.Descriptor instead.
func (*CreateReplyAreaReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{21}
}

type UpdateReplyAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReplyAreaRequest) Reset() {
	*x = UpdateReplyAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReplyAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplyAreaRequest) ProtoMessage() {}

func (x *UpdateReplyAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplyAreaRequest.ProtoReflect.Descriptor instead.
func (*UpdateReplyAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{22}
}

type UpdateReplyAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReplyAreaReply) Reset() {
	*x = UpdateReplyAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReplyAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplyAreaReply) ProtoMessage() {}

func (x *UpdateReplyAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplyAreaReply.ProtoReflect.Descriptor instead.
func (*UpdateReplyAreaReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{23}
}

type GetReplyAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReplyAreaRequest) Reset() {
	*x = GetReplyAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplyAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyAreaRequest) ProtoMessage() {}

func (x *GetReplyAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyAreaRequest.ProtoReflect.Descriptor instead.
func (*GetReplyAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{24}
}

type GetReplyAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReplyAreaReply) Reset() {
	*x = GetReplyAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplyAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyAreaReply) ProtoMessage() {}

func (x *GetReplyAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyAreaReply.ProtoReflect.Descriptor instead.
func (*GetReplyAreaReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{25}
}

type DeleteReplyAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReplyAreaRequest) Reset() {
	*x = DeleteReplyAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReplyAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyAreaRequest) ProtoMessage() {}

func (x *DeleteReplyAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyAreaRequest.ProtoReflect.Descriptor instead.
func (*DeleteReplyAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{26}
}

type DeleteReplyAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReplyAreaReply) Reset() {
	*x = DeleteReplyAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReplyAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyAreaReply) ProtoMessage() {}

func (x *DeleteReplyAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyAreaReply.ProtoReflect.Descriptor instead.
func (*DeleteReplyAreaReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{27}
}

type ListReplyAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListReplyAreaRequest) Reset() {
	*x = ListReplyAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReplyAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplyAreaRequest) ProtoMessage() {}

func (x *ListReplyAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplyAreaRequest.ProtoReflect.Descriptor instead.
func (*ListReplyAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{28}
}

type ListReplyAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListReplyAreaReply) Reset() {
	*x = ListReplyAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentService_v1_commentService_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReplyAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplyAreaReply) ProtoMessage() {}

func (x *ListReplyAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentService_v1_commentService_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplyAreaReply.ProtoReflect.Descriptor instead.
func (*ListReplyAreaReply) Descriptor() ([]byte, []int) {
	return file_api_commentService_v1_commentService_proto_rawDescGZIP(), []int{29}
}

var File_api_commentService_v1_commentService_proto protoreflect.FileDescriptor

var file_api_commentService_v1_commentService_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a, 0x17,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x15, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41,
	0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41,
	0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xdc, 0x0c, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x0b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x63, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x63, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5a, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5d, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x74, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x72, 0x0a, 0x10, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x72, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x69, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6c,
	0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x72, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x12,
	0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x6f, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41,
	0x72, 0x65, 0x61, 0x12, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x6f, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x41, 0x72, 0x65, 0x61, 0x12, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x66, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72,
	0x65, 0x61, 0x12, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x69, 0x0a, 0x0d, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61, 0x12, 0x2c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72,
	0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x65, 0x61,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x40, 0x0a, 0x15, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01,
	0x5a, 0x25, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_commentService_v1_commentService_proto_rawDescOnce sync.Once
	file_api_commentService_v1_commentService_proto_rawDescData = file_api_commentService_v1_commentService_proto_rawDesc
)

func file_api_commentService_v1_commentService_proto_rawDescGZIP() []byte {
	file_api_commentService_v1_commentService_proto_rawDescOnce.Do(func() {
		file_api_commentService_v1_commentService_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_commentService_v1_commentService_proto_rawDescData)
	})
	return file_api_commentService_v1_commentService_proto_rawDescData
}

var file_api_commentService_v1_commentService_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_api_commentService_v1_commentService_proto_goTypes = []interface{}{
	(*CreateReplyRequest)(nil),      // 0: api.comment.service.v1.CreateReplyRequest
	(*CreateReplyReply)(nil),        // 1: api.comment.service.v1.CreateReplyReply
	(*UpdateReplyRequest)(nil),      // 2: api.comment.service.v1.UpdateReplyRequest
	(*UpdateReplyReply)(nil),        // 3: api.comment.service.v1.UpdateReplyReply
	(*DeleteReplyRequest)(nil),      // 4: api.comment.service.v1.DeleteReplyRequest
	(*DeleteReplyReply)(nil),        // 5: api.comment.service.v1.DeleteReplyReply
	(*GetReplyRequest)(nil),         // 6: api.comment.service.v1.GetReplyRequest
	(*GetReplyReply)(nil),           // 7: api.comment.service.v1.GetReplyReply
	(*ListReplyRequest)(nil),        // 8: api.comment.service.v1.ListReplyRequest
	(*ListReplyReply)(nil),          // 9: api.comment.service.v1.ListReplyReply
	(*CreateReplyIndexRequest)(nil), // 10: api.comment.service.v1.CreateReplyIndexRequest
	(*CreateReplyIndexReply)(nil),   // 11: api.comment.service.v1.CreateReplyIndexReply
	(*UpdateReplyIndexRequest)(nil), // 12: api.comment.service.v1.UpdateReplyIndexRequest
	(*UpdateReplyIndexReply)(nil),   // 13: api.comment.service.v1.UpdateReplyIndexReply
	(*DeleteReplyIndexRequest)(nil), // 14: api.comment.service.v1.DeleteReplyIndexRequest
	(*DeleteReplyIndexReply)(nil),   // 15: api.comment.service.v1.DeleteReplyIndexReply
	(*GetReplyIndexRequest)(nil),    // 16: api.comment.service.v1.GetReplyIndexRequest
	(*GetReplyIndexReply)(nil),      // 17: api.comment.service.v1.GetReplyIndexReply
	(*ListReplyIndexRequest)(nil),   // 18: api.comment.service.v1.ListReplyIndexRequest
	(*ListReplyIndexReply)(nil),     // 19: api.comment.service.v1.ListReplyIndexReply
	(*CreateReplyAreaRequest)(nil),  // 20: api.comment.service.v1.CreateReplyAreaRequest
	(*CreateReplyAreaReply)(nil),    // 21: api.comment.service.v1.CreateReplyAreaReply
	(*UpdateReplyAreaRequest)(nil),  // 22: api.comment.service.v1.UpdateReplyAreaRequest
	(*UpdateReplyAreaReply)(nil),    // 23: api.comment.service.v1.UpdateReplyAreaReply
	(*GetReplyAreaRequest)(nil),     // 24: api.comment.service.v1.GetReplyAreaRequest
	(*GetReplyAreaReply)(nil),       // 25: api.comment.service.v1.GetReplyAreaReply
	(*DeleteReplyAreaRequest)(nil),  // 26: api.comment.service.v1.DeleteReplyAreaRequest
	(*DeleteReplyAreaReply)(nil),    // 27: api.comment.service.v1.DeleteReplyAreaReply
	(*ListReplyAreaRequest)(nil),    // 28: api.comment.service.v1.ListReplyAreaRequest
	(*ListReplyAreaReply)(nil),      // 29: api.comment.service.v1.ListReplyAreaReply
}
var file_api_commentService_v1_commentService_proto_depIdxs = []int32{
	0,  // 0: api.comment.service.v1.CommentService.CreateReply:input_type -> api.comment.service.v1.CreateReplyRequest
	2,  // 1: api.comment.service.v1.CommentService.UpdateReply:input_type -> api.comment.service.v1.UpdateReplyRequest
	4,  // 2: api.comment.service.v1.CommentService.DeleteReply:input_type -> api.comment.service.v1.DeleteReplyRequest
	6,  // 3: api.comment.service.v1.CommentService.GetReply:input_type -> api.comment.service.v1.GetReplyRequest
	8,  // 4: api.comment.service.v1.CommentService.ListReply:input_type -> api.comment.service.v1.ListReplyRequest
	10, // 5: api.comment.service.v1.CommentService.CreateReplyIndex:input_type -> api.comment.service.v1.CreateReplyIndexRequest
	12, // 6: api.comment.service.v1.CommentService.UpdateReplyIndex:input_type -> api.comment.service.v1.UpdateReplyIndexRequest
	14, // 7: api.comment.service.v1.CommentService.DeleteReplyIndex:input_type -> api.comment.service.v1.DeleteReplyIndexRequest
	16, // 8: api.comment.service.v1.CommentService.GetReplyIndex:input_type -> api.comment.service.v1.GetReplyIndexRequest
	18, // 9: api.comment.service.v1.CommentService.ListReplyIndex:input_type -> api.comment.service.v1.ListReplyIndexRequest
	10, // 10: api.comment.service.v1.CommentService.CreateReplyArea:input_type -> api.comment.service.v1.CreateReplyIndexRequest
	22, // 11: api.comment.service.v1.CommentService.UpdateReplyArea:input_type -> api.comment.service.v1.UpdateReplyAreaRequest
	26, // 12: api.comment.service.v1.CommentService.DeleteReplyArea:input_type -> api.comment.service.v1.DeleteReplyAreaRequest
	24, // 13: api.comment.service.v1.CommentService.GetReplyArea:input_type -> api.comment.service.v1.GetReplyAreaRequest
	28, // 14: api.comment.service.v1.CommentService.ListReplyArea:input_type -> api.comment.service.v1.ListReplyAreaRequest
	1,  // 15: api.comment.service.v1.CommentService.CreateReply:output_type -> api.comment.service.v1.CreateReplyReply
	3,  // 16: api.comment.service.v1.CommentService.UpdateReply:output_type -> api.comment.service.v1.UpdateReplyReply
	5,  // 17: api.comment.service.v1.CommentService.DeleteReply:output_type -> api.comment.service.v1.DeleteReplyReply
	7,  // 18: api.comment.service.v1.CommentService.GetReply:output_type -> api.comment.service.v1.GetReplyReply
	9,  // 19: api.comment.service.v1.CommentService.ListReply:output_type -> api.comment.service.v1.ListReplyReply
	11, // 20: api.comment.service.v1.CommentService.CreateReplyIndex:output_type -> api.comment.service.v1.CreateReplyIndexReply
	13, // 21: api.comment.service.v1.CommentService.UpdateReplyIndex:output_type -> api.comment.service.v1.UpdateReplyIndexReply
	15, // 22: api.comment.service.v1.CommentService.DeleteReplyIndex:output_type -> api.comment.service.v1.DeleteReplyIndexReply
	17, // 23: api.comment.service.v1.CommentService.GetReplyIndex:output_type -> api.comment.service.v1.GetReplyIndexReply
	19, // 24: api.comment.service.v1.CommentService.ListReplyIndex:output_type -> api.comment.service.v1.ListReplyIndexReply
	21, // 25: api.comment.service.v1.CommentService.CreateReplyArea:output_type -> api.comment.service.v1.CreateReplyAreaReply
	23, // 26: api.comment.service.v1.CommentService.UpdateReplyArea:output_type -> api.comment.service.v1.UpdateReplyAreaReply
	27, // 27: api.comment.service.v1.CommentService.DeleteReplyArea:output_type -> api.comment.service.v1.DeleteReplyAreaReply
	25, // 28: api.comment.service.v1.CommentService.GetReplyArea:output_type -> api.comment.service.v1.GetReplyAreaReply
	29, // 29: api.comment.service.v1.CommentService.ListReplyArea:output_type -> api.comment.service.v1.ListReplyAreaReply
	15, // [15:30] is the sub-list for method output_type
	0,  // [0:15] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_commentService_v1_commentService_proto_init() }
func file_api_commentService_v1_commentService_proto_init() {
	if File_api_commentService_v1_commentService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_commentService_v1_commentService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReplyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReplyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReplyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReplyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReplyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReplyIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReplyIndexReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReplyIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReplyIndexReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReplyIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReplyIndexReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReplyIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReplyIndexReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReplyIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReplyIndexReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReplyAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReplyAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReplyAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReplyAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReplyAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReplyAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReplyAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReplyAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReplyAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentService_v1_commentService_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReplyAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_commentService_v1_commentService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_commentService_v1_commentService_proto_goTypes,
		DependencyIndexes: file_api_commentService_v1_commentService_proto_depIdxs,
		MessageInfos:      file_api_commentService_v1_commentService_proto_msgTypes,
	}.Build()
	File_api_commentService_v1_commentService_proto = out.File
	file_api_commentService_v1_commentService_proto_rawDesc = nil
	file_api_commentService_v1_commentService_proto_goTypes = nil
	file_api_commentService_v1_commentService_proto_depIdxs = nil
}
