// Code generated by ent, DO NOT EDIT.

package ent

import (
	"comment-main/app/comment-service/internal/data/ent/predicate"
	"comment-main/app/comment-service/internal/data/ent/replyarea"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReplyAreaDelete is the builder for deleting a ReplyArea entity.
type ReplyAreaDelete struct {
	config
	hooks    []Hook
	mutation *ReplyAreaMutation
}

// Where appends a list predicates to the ReplyAreaDelete builder.
func (rad *ReplyAreaDelete) Where(ps ...predicate.ReplyArea) *ReplyAreaDelete {
	rad.mutation.Where(ps...)
	return rad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rad *ReplyAreaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rad.sqlExec, rad.mutation, rad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rad *ReplyAreaDelete) ExecX(ctx context.Context) int {
	n, err := rad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rad *ReplyAreaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(replyarea.Table, sqlgraph.NewFieldSpec(replyarea.FieldID, field.TypeInt64))
	if ps := rad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rad.mutation.done = true
	return affected, err
}

// ReplyAreaDeleteOne is the builder for deleting a single ReplyArea entity.
type ReplyAreaDeleteOne struct {
	rad *ReplyAreaDelete
}

// Where appends a list predicates to the ReplyAreaDelete builder.
func (rado *ReplyAreaDeleteOne) Where(ps ...predicate.ReplyArea) *ReplyAreaDeleteOne {
	rado.rad.mutation.Where(ps...)
	return rado
}

// Exec executes the deletion query.
func (rado *ReplyAreaDeleteOne) Exec(ctx context.Context) error {
	n, err := rado.rad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{replyarea.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rado *ReplyAreaDeleteOne) ExecX(ctx context.Context) {
	if err := rado.Exec(ctx); err != nil {
		panic(err)
	}
}
