// Code generated by ent, DO NOT EDIT.

package ent

import (
	"comment-main/app/comment-service/internal/data/ent/predicate"
	"comment-main/app/comment-service/internal/data/ent/replyarea"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReplyAreaQuery is the builder for querying ReplyArea entities.
type ReplyAreaQuery struct {
	config
	ctx        *QueryContext
	order      []replyarea.OrderOption
	inters     []Interceptor
	predicates []predicate.ReplyArea
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReplyAreaQuery builder.
func (raq *ReplyAreaQuery) Where(ps ...predicate.ReplyArea) *ReplyAreaQuery {
	raq.predicates = append(raq.predicates, ps...)
	return raq
}

// Limit the number of records to be returned by this query.
func (raq *ReplyAreaQuery) Limit(limit int) *ReplyAreaQuery {
	raq.ctx.Limit = &limit
	return raq
}

// Offset to start from.
func (raq *ReplyAreaQuery) Offset(offset int) *ReplyAreaQuery {
	raq.ctx.Offset = &offset
	return raq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (raq *ReplyAreaQuery) Unique(unique bool) *ReplyAreaQuery {
	raq.ctx.Unique = &unique
	return raq
}

// Order specifies how the records should be ordered.
func (raq *ReplyAreaQuery) Order(o ...replyarea.OrderOption) *ReplyAreaQuery {
	raq.order = append(raq.order, o...)
	return raq
}

// First returns the first ReplyArea entity from the query.
// Returns a *NotFoundError when no ReplyArea was found.
func (raq *ReplyAreaQuery) First(ctx context.Context) (*ReplyArea, error) {
	nodes, err := raq.Limit(1).All(setContextOp(ctx, raq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{replyarea.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (raq *ReplyAreaQuery) FirstX(ctx context.Context) *ReplyArea {
	node, err := raq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReplyArea ID from the query.
// Returns a *NotFoundError when no ReplyArea ID was found.
func (raq *ReplyAreaQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = raq.Limit(1).IDs(setContextOp(ctx, raq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{replyarea.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (raq *ReplyAreaQuery) FirstIDX(ctx context.Context) int64 {
	id, err := raq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReplyArea entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReplyArea entity is found.
// Returns a *NotFoundError when no ReplyArea entities are found.
func (raq *ReplyAreaQuery) Only(ctx context.Context) (*ReplyArea, error) {
	nodes, err := raq.Limit(2).All(setContextOp(ctx, raq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{replyarea.Label}
	default:
		return nil, &NotSingularError{replyarea.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (raq *ReplyAreaQuery) OnlyX(ctx context.Context) *ReplyArea {
	node, err := raq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReplyArea ID in the query.
// Returns a *NotSingularError when more than one ReplyArea ID is found.
// Returns a *NotFoundError when no entities are found.
func (raq *ReplyAreaQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = raq.Limit(2).IDs(setContextOp(ctx, raq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{replyarea.Label}
	default:
		err = &NotSingularError{replyarea.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (raq *ReplyAreaQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := raq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReplyAreas.
func (raq *ReplyAreaQuery) All(ctx context.Context) ([]*ReplyArea, error) {
	ctx = setContextOp(ctx, raq.ctx, "All")
	if err := raq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReplyArea, *ReplyAreaQuery]()
	return withInterceptors[[]*ReplyArea](ctx, raq, qr, raq.inters)
}

// AllX is like All, but panics if an error occurs.
func (raq *ReplyAreaQuery) AllX(ctx context.Context) []*ReplyArea {
	nodes, err := raq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReplyArea IDs.
func (raq *ReplyAreaQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if raq.ctx.Unique == nil && raq.path != nil {
		raq.Unique(true)
	}
	ctx = setContextOp(ctx, raq.ctx, "IDs")
	if err = raq.Select(replyarea.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (raq *ReplyAreaQuery) IDsX(ctx context.Context) []int64 {
	ids, err := raq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (raq *ReplyAreaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, raq.ctx, "Count")
	if err := raq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, raq, querierCount[*ReplyAreaQuery](), raq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (raq *ReplyAreaQuery) CountX(ctx context.Context) int {
	count, err := raq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (raq *ReplyAreaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, raq.ctx, "Exist")
	switch _, err := raq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (raq *ReplyAreaQuery) ExistX(ctx context.Context) bool {
	exist, err := raq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReplyAreaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (raq *ReplyAreaQuery) Clone() *ReplyAreaQuery {
	if raq == nil {
		return nil
	}
	return &ReplyAreaQuery{
		config:     raq.config,
		ctx:        raq.ctx.Clone(),
		order:      append([]replyarea.OrderOption{}, raq.order...),
		inters:     append([]Interceptor{}, raq.inters...),
		predicates: append([]predicate.ReplyArea{}, raq.predicates...),
		// clone intermediate query.
		sql:  raq.sql.Clone(),
		path: raq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Oid int64 `json:"oid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReplyArea.Query().
//		GroupBy(replyarea.FieldOid).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (raq *ReplyAreaQuery) GroupBy(field string, fields ...string) *ReplyAreaGroupBy {
	raq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReplyAreaGroupBy{build: raq}
	grbuild.flds = &raq.ctx.Fields
	grbuild.label = replyarea.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Oid int64 `json:"oid,omitempty"`
//	}
//
//	client.ReplyArea.Query().
//		Select(replyarea.FieldOid).
//		Scan(ctx, &v)
func (raq *ReplyAreaQuery) Select(fields ...string) *ReplyAreaSelect {
	raq.ctx.Fields = append(raq.ctx.Fields, fields...)
	sbuild := &ReplyAreaSelect{ReplyAreaQuery: raq}
	sbuild.label = replyarea.Label
	sbuild.flds, sbuild.scan = &raq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReplyAreaSelect configured with the given aggregations.
func (raq *ReplyAreaQuery) Aggregate(fns ...AggregateFunc) *ReplyAreaSelect {
	return raq.Select().Aggregate(fns...)
}

func (raq *ReplyAreaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range raq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, raq); err != nil {
				return err
			}
		}
	}
	for _, f := range raq.ctx.Fields {
		if !replyarea.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if raq.path != nil {
		prev, err := raq.path(ctx)
		if err != nil {
			return err
		}
		raq.sql = prev
	}
	return nil
}

func (raq *ReplyAreaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReplyArea, error) {
	var (
		nodes = []*ReplyArea{}
		_spec = raq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReplyArea).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReplyArea{config: raq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, raq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (raq *ReplyAreaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := raq.querySpec()
	_spec.Node.Columns = raq.ctx.Fields
	if len(raq.ctx.Fields) > 0 {
		_spec.Unique = raq.ctx.Unique != nil && *raq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, raq.driver, _spec)
}

func (raq *ReplyAreaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(replyarea.Table, replyarea.Columns, sqlgraph.NewFieldSpec(replyarea.FieldID, field.TypeInt64))
	_spec.From = raq.sql
	if unique := raq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if raq.path != nil {
		_spec.Unique = true
	}
	if fields := raq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, replyarea.FieldID)
		for i := range fields {
			if fields[i] != replyarea.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := raq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := raq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := raq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := raq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (raq *ReplyAreaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(raq.driver.Dialect())
	t1 := builder.Table(replyarea.Table)
	columns := raq.ctx.Fields
	if len(columns) == 0 {
		columns = replyarea.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if raq.sql != nil {
		selector = raq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if raq.ctx.Unique != nil && *raq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range raq.predicates {
		p(selector)
	}
	for _, p := range raq.order {
		p(selector)
	}
	if offset := raq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := raq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReplyAreaGroupBy is the group-by builder for ReplyArea entities.
type ReplyAreaGroupBy struct {
	selector
	build *ReplyAreaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ragb *ReplyAreaGroupBy) Aggregate(fns ...AggregateFunc) *ReplyAreaGroupBy {
	ragb.fns = append(ragb.fns, fns...)
	return ragb
}

// Scan applies the selector query and scans the result into the given value.
func (ragb *ReplyAreaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ragb.build.ctx, "GroupBy")
	if err := ragb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReplyAreaQuery, *ReplyAreaGroupBy](ctx, ragb.build, ragb, ragb.build.inters, v)
}

func (ragb *ReplyAreaGroupBy) sqlScan(ctx context.Context, root *ReplyAreaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ragb.fns))
	for _, fn := range ragb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ragb.flds)+len(ragb.fns))
		for _, f := range *ragb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ragb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ragb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReplyAreaSelect is the builder for selecting fields of ReplyArea entities.
type ReplyAreaSelect struct {
	*ReplyAreaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ras *ReplyAreaSelect) Aggregate(fns ...AggregateFunc) *ReplyAreaSelect {
	ras.fns = append(ras.fns, fns...)
	return ras
}

// Scan applies the selector query and scans the result into the given value.
func (ras *ReplyAreaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ras.ctx, "Select")
	if err := ras.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReplyAreaQuery, *ReplyAreaSelect](ctx, ras.ReplyAreaQuery, ras, ras.inters, v)
}

func (ras *ReplyAreaSelect) sqlScan(ctx context.Context, root *ReplyAreaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ras.fns))
	for _, fn := range ras.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ras.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ras.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
