// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entcdemo/ent/reply"
	"entcdemo/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	replyFields := schema.Reply{}.Fields()
	_ = replyFields
	// replyDescCtime is the schema descriptor for ctime field.
	replyDescCtime := replyFields[7].Descriptor()
	// reply.DefaultCtime holds the default value on creation for the ctime field.
	reply.DefaultCtime = replyDescCtime.Default.(func() time.Time)
	// replyDescMtime is the schema descriptor for mtime field.
	replyDescMtime := replyFields[8].Descriptor()
	// reply.DefaultMtime holds the default value on creation for the mtime field.
	reply.DefaultMtime = replyDescMtime.Default.(func() time.Time)
}
