// Code generated by ent, DO NOT EDIT.

package replyarea

import (
	"comment-main/app/comment-service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLTE(FieldID, id))
}

// Oid applies equality check predicate on the "oid" field. It's identical to OidEQ.
func Oid(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldOid, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldType, v))
}

// Mid applies equality check predicate on the "mid" field. It's identical to MidEQ.
func Mid(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldMid, v))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldCount, v))
}

// RootCount applies equality check predicate on the "root_count" field. It's identical to RootCountEQ.
func RootCount(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldRootCount, v))
}

// Acount applies equality check predicate on the "acount" field. It's identical to AcountEQ.
func Acount(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldAcount, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldState, v))
}

// Ctime applies equality check predicate on the "ctime" field. It's identical to CtimeEQ.
func Ctime(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldCtime, v))
}

// Mtime applies equality check predicate on the "mtime" field. It's identical to MtimeEQ.
func Mtime(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldMtime, v))
}

// Attrs applies equality check predicate on the "attrs" field. It's identical to AttrsEQ.
func Attrs(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldAttrs, v))
}

// Meta applies equality check predicate on the "meta" field. It's identical to MetaEQ.
func Meta(v string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldMeta, v))
}

// OidEQ applies the EQ predicate on the "oid" field.
func OidEQ(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldOid, v))
}

// OidNEQ applies the NEQ predicate on the "oid" field.
func OidNEQ(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNEQ(FieldOid, v))
}

// OidIn applies the In predicate on the "oid" field.
func OidIn(vs ...int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldIn(FieldOid, vs...))
}

// OidNotIn applies the NotIn predicate on the "oid" field.
func OidNotIn(vs ...int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNotIn(FieldOid, vs...))
}

// OidGT applies the GT predicate on the "oid" field.
func OidGT(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGT(FieldOid, v))
}

// OidGTE applies the GTE predicate on the "oid" field.
func OidGTE(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGTE(FieldOid, v))
}

// OidLT applies the LT predicate on the "oid" field.
func OidLT(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLT(FieldOid, v))
}

// OidLTE applies the LTE predicate on the "oid" field.
func OidLTE(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLTE(FieldOid, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLTE(FieldType, v))
}

// MidEQ applies the EQ predicate on the "mid" field.
func MidEQ(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldMid, v))
}

// MidNEQ applies the NEQ predicate on the "mid" field.
func MidNEQ(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNEQ(FieldMid, v))
}

// MidIn applies the In predicate on the "mid" field.
func MidIn(vs ...int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldIn(FieldMid, vs...))
}

// MidNotIn applies the NotIn predicate on the "mid" field.
func MidNotIn(vs ...int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNotIn(FieldMid, vs...))
}

// MidGT applies the GT predicate on the "mid" field.
func MidGT(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGT(FieldMid, v))
}

// MidGTE applies the GTE predicate on the "mid" field.
func MidGTE(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGTE(FieldMid, v))
}

// MidLT applies the LT predicate on the "mid" field.
func MidLT(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLT(FieldMid, v))
}

// MidLTE applies the LTE predicate on the "mid" field.
func MidLTE(v int64) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLTE(FieldMid, v))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLTE(FieldCount, v))
}

// RootCountEQ applies the EQ predicate on the "root_count" field.
func RootCountEQ(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldRootCount, v))
}

// RootCountNEQ applies the NEQ predicate on the "root_count" field.
func RootCountNEQ(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNEQ(FieldRootCount, v))
}

// RootCountIn applies the In predicate on the "root_count" field.
func RootCountIn(vs ...int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldIn(FieldRootCount, vs...))
}

// RootCountNotIn applies the NotIn predicate on the "root_count" field.
func RootCountNotIn(vs ...int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNotIn(FieldRootCount, vs...))
}

// RootCountGT applies the GT predicate on the "root_count" field.
func RootCountGT(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGT(FieldRootCount, v))
}

// RootCountGTE applies the GTE predicate on the "root_count" field.
func RootCountGTE(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGTE(FieldRootCount, v))
}

// RootCountLT applies the LT predicate on the "root_count" field.
func RootCountLT(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLT(FieldRootCount, v))
}

// RootCountLTE applies the LTE predicate on the "root_count" field.
func RootCountLTE(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLTE(FieldRootCount, v))
}

// AcountEQ applies the EQ predicate on the "acount" field.
func AcountEQ(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldAcount, v))
}

// AcountNEQ applies the NEQ predicate on the "acount" field.
func AcountNEQ(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNEQ(FieldAcount, v))
}

// AcountIn applies the In predicate on the "acount" field.
func AcountIn(vs ...int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldIn(FieldAcount, vs...))
}

// AcountNotIn applies the NotIn predicate on the "acount" field.
func AcountNotIn(vs ...int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNotIn(FieldAcount, vs...))
}

// AcountGT applies the GT predicate on the "acount" field.
func AcountGT(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGT(FieldAcount, v))
}

// AcountGTE applies the GTE predicate on the "acount" field.
func AcountGTE(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGTE(FieldAcount, v))
}

// AcountLT applies the LT predicate on the "acount" field.
func AcountLT(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLT(FieldAcount, v))
}

// AcountLTE applies the LTE predicate on the "acount" field.
func AcountLTE(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLTE(FieldAcount, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v int8) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLTE(FieldState, v))
}

// CtimeEQ applies the EQ predicate on the "ctime" field.
func CtimeEQ(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldCtime, v))
}

// CtimeNEQ applies the NEQ predicate on the "ctime" field.
func CtimeNEQ(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNEQ(FieldCtime, v))
}

// CtimeIn applies the In predicate on the "ctime" field.
func CtimeIn(vs ...time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldIn(FieldCtime, vs...))
}

// CtimeNotIn applies the NotIn predicate on the "ctime" field.
func CtimeNotIn(vs ...time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNotIn(FieldCtime, vs...))
}

// CtimeGT applies the GT predicate on the "ctime" field.
func CtimeGT(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGT(FieldCtime, v))
}

// CtimeGTE applies the GTE predicate on the "ctime" field.
func CtimeGTE(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGTE(FieldCtime, v))
}

// CtimeLT applies the LT predicate on the "ctime" field.
func CtimeLT(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLT(FieldCtime, v))
}

// CtimeLTE applies the LTE predicate on the "ctime" field.
func CtimeLTE(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLTE(FieldCtime, v))
}

// MtimeEQ applies the EQ predicate on the "mtime" field.
func MtimeEQ(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldMtime, v))
}

// MtimeNEQ applies the NEQ predicate on the "mtime" field.
func MtimeNEQ(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNEQ(FieldMtime, v))
}

// MtimeIn applies the In predicate on the "mtime" field.
func MtimeIn(vs ...time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldIn(FieldMtime, vs...))
}

// MtimeNotIn applies the NotIn predicate on the "mtime" field.
func MtimeNotIn(vs ...time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNotIn(FieldMtime, vs...))
}

// MtimeGT applies the GT predicate on the "mtime" field.
func MtimeGT(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGT(FieldMtime, v))
}

// MtimeGTE applies the GTE predicate on the "mtime" field.
func MtimeGTE(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGTE(FieldMtime, v))
}

// MtimeLT applies the LT predicate on the "mtime" field.
func MtimeLT(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLT(FieldMtime, v))
}

// MtimeLTE applies the LTE predicate on the "mtime" field.
func MtimeLTE(v time.Time) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLTE(FieldMtime, v))
}

// AttrsEQ applies the EQ predicate on the "attrs" field.
func AttrsEQ(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldAttrs, v))
}

// AttrsNEQ applies the NEQ predicate on the "attrs" field.
func AttrsNEQ(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNEQ(FieldAttrs, v))
}

// AttrsIn applies the In predicate on the "attrs" field.
func AttrsIn(vs ...int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldIn(FieldAttrs, vs...))
}

// AttrsNotIn applies the NotIn predicate on the "attrs" field.
func AttrsNotIn(vs ...int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNotIn(FieldAttrs, vs...))
}

// AttrsGT applies the GT predicate on the "attrs" field.
func AttrsGT(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGT(FieldAttrs, v))
}

// AttrsGTE applies the GTE predicate on the "attrs" field.
func AttrsGTE(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGTE(FieldAttrs, v))
}

// AttrsLT applies the LT predicate on the "attrs" field.
func AttrsLT(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLT(FieldAttrs, v))
}

// AttrsLTE applies the LTE predicate on the "attrs" field.
func AttrsLTE(v int32) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLTE(FieldAttrs, v))
}

// MetaEQ applies the EQ predicate on the "meta" field.
func MetaEQ(v string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEQ(FieldMeta, v))
}

// MetaNEQ applies the NEQ predicate on the "meta" field.
func MetaNEQ(v string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNEQ(FieldMeta, v))
}

// MetaIn applies the In predicate on the "meta" field.
func MetaIn(vs ...string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldIn(FieldMeta, vs...))
}

// MetaNotIn applies the NotIn predicate on the "meta" field.
func MetaNotIn(vs ...string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldNotIn(FieldMeta, vs...))
}

// MetaGT applies the GT predicate on the "meta" field.
func MetaGT(v string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGT(FieldMeta, v))
}

// MetaGTE applies the GTE predicate on the "meta" field.
func MetaGTE(v string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldGTE(FieldMeta, v))
}

// MetaLT applies the LT predicate on the "meta" field.
func MetaLT(v string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLT(FieldMeta, v))
}

// MetaLTE applies the LTE predicate on the "meta" field.
func MetaLTE(v string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldLTE(FieldMeta, v))
}

// MetaContains applies the Contains predicate on the "meta" field.
func MetaContains(v string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldContains(FieldMeta, v))
}

// MetaHasPrefix applies the HasPrefix predicate on the "meta" field.
func MetaHasPrefix(v string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldHasPrefix(FieldMeta, v))
}

// MetaHasSuffix applies the HasSuffix predicate on the "meta" field.
func MetaHasSuffix(v string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldHasSuffix(FieldMeta, v))
}

// MetaEqualFold applies the EqualFold predicate on the "meta" field.
func MetaEqualFold(v string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldEqualFold(FieldMeta, v))
}

// MetaContainsFold applies the ContainsFold predicate on the "meta" field.
func MetaContainsFold(v string) predicate.ReplyArea {
	return predicate.ReplyArea(sql.FieldContainsFold(FieldMeta, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReplyArea) predicate.ReplyArea {
	return predicate.ReplyArea(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReplyArea) predicate.ReplyArea {
	return predicate.ReplyArea(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReplyArea) predicate.ReplyArea {
	return predicate.ReplyArea(func(s *sql.Selector) {
		p(s.Not())
	})
}
