// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: api/accountService/v1/accountService.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAccountServiceRequest) Reset() {
	*x = CreateAccountServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_accountService_v1_accountService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccountServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountServiceRequest) ProtoMessage() {}

func (x *CreateAccountServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_accountService_v1_accountService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_accountService_v1_accountService_proto_rawDescGZIP(), []int{0}
}

type CreateAccountServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAccountServiceReply) Reset() {
	*x = CreateAccountServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_accountService_v1_accountService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccountServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountServiceReply) ProtoMessage() {}

func (x *CreateAccountServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_accountService_v1_accountService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountServiceReply.ProtoReflect.Descriptor instead.
func (*CreateAccountServiceReply) Descriptor() ([]byte, []int) {
	return file_api_accountService_v1_accountService_proto_rawDescGZIP(), []int{1}
}

type UpdateAccountServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAccountServiceRequest) Reset() {
	*x = UpdateAccountServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_accountService_v1_accountService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAccountServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountServiceRequest) ProtoMessage() {}

func (x *UpdateAccountServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_accountService_v1_accountService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_accountService_v1_accountService_proto_rawDescGZIP(), []int{2}
}

type UpdateAccountServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAccountServiceReply) Reset() {
	*x = UpdateAccountServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_accountService_v1_accountService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAccountServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountServiceReply) ProtoMessage() {}

func (x *UpdateAccountServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_accountService_v1_accountService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountServiceReply.ProtoReflect.Descriptor instead.
func (*UpdateAccountServiceReply) Descriptor() ([]byte, []int) {
	return file_api_accountService_v1_accountService_proto_rawDescGZIP(), []int{3}
}

type DeleteAccountServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAccountServiceRequest) Reset() {
	*x = DeleteAccountServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_accountService_v1_accountService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAccountServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountServiceRequest) ProtoMessage() {}

func (x *DeleteAccountServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_accountService_v1_accountService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_accountService_v1_accountService_proto_rawDescGZIP(), []int{4}
}

type DeleteAccountServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAccountServiceReply) Reset() {
	*x = DeleteAccountServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_accountService_v1_accountService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAccountServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountServiceReply) ProtoMessage() {}

func (x *DeleteAccountServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_accountService_v1_accountService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountServiceReply.ProtoReflect.Descriptor instead.
func (*DeleteAccountServiceReply) Descriptor() ([]byte, []int) {
	return file_api_accountService_v1_accountService_proto_rawDescGZIP(), []int{5}
}

type GetAccountServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAccountServiceRequest) Reset() {
	*x = GetAccountServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_accountService_v1_accountService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountServiceRequest) ProtoMessage() {}

func (x *GetAccountServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_accountService_v1_accountService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountServiceRequest.ProtoReflect.Descriptor instead.
func (*GetAccountServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_accountService_v1_accountService_proto_rawDescGZIP(), []int{6}
}

type GetAccountServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAccountServiceReply) Reset() {
	*x = GetAccountServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_accountService_v1_accountService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountServiceReply) ProtoMessage() {}

func (x *GetAccountServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_accountService_v1_accountService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountServiceReply.ProtoReflect.Descriptor instead.
func (*GetAccountServiceReply) Descriptor() ([]byte, []int) {
	return file_api_accountService_v1_accountService_proto_rawDescGZIP(), []int{7}
}

type ListAccountServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAccountServiceRequest) Reset() {
	*x = ListAccountServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_accountService_v1_accountService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAccountServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountServiceRequest) ProtoMessage() {}

func (x *ListAccountServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_accountService_v1_accountService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountServiceRequest.ProtoReflect.Descriptor instead.
func (*ListAccountServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_accountService_v1_accountService_proto_rawDescGZIP(), []int{8}
}

type ListAccountServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAccountServiceReply) Reset() {
	*x = ListAccountServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_accountService_v1_accountService_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAccountServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountServiceReply) ProtoMessage() {}

func (x *ListAccountServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_accountService_v1_accountService_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountServiceReply.ProtoReflect.Descriptor instead.
func (*ListAccountServiceReply) Descriptor() ([]byte, []int) {
	return file_api_accountService_v1_accountService_proto_rawDescGZIP(), []int{9}
}

var File_api_accountService_v1_accountService_proto protoreflect.FileDescriptor

var file_api_accountService_v1_accountService_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1d, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1b, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x0a, 0x1b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b,
	0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x81, 0x05, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7e, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x7e, 0x0a, 0x14, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x7e, 0x0a, 0x14, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x75, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x78, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x40, 0x0a, 0x15, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x25, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x6d,
	0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_accountService_v1_accountService_proto_rawDescOnce sync.Once
	file_api_accountService_v1_accountService_proto_rawDescData = file_api_accountService_v1_accountService_proto_rawDesc
)

func file_api_accountService_v1_accountService_proto_rawDescGZIP() []byte {
	file_api_accountService_v1_accountService_proto_rawDescOnce.Do(func() {
		file_api_accountService_v1_accountService_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_accountService_v1_accountService_proto_rawDescData)
	})
	return file_api_accountService_v1_accountService_proto_rawDescData
}

var file_api_accountService_v1_accountService_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_accountService_v1_accountService_proto_goTypes = []interface{}{
	(*CreateAccountServiceRequest)(nil), // 0: api.account.service.v1.CreateAccountServiceRequest
	(*CreateAccountServiceReply)(nil),   // 1: api.account.service.v1.CreateAccountServiceReply
	(*UpdateAccountServiceRequest)(nil), // 2: api.account.service.v1.UpdateAccountServiceRequest
	(*UpdateAccountServiceReply)(nil),   // 3: api.account.service.v1.UpdateAccountServiceReply
	(*DeleteAccountServiceRequest)(nil), // 4: api.account.service.v1.DeleteAccountServiceRequest
	(*DeleteAccountServiceReply)(nil),   // 5: api.account.service.v1.DeleteAccountServiceReply
	(*GetAccountServiceRequest)(nil),    // 6: api.account.service.v1.GetAccountServiceRequest
	(*GetAccountServiceReply)(nil),      // 7: api.account.service.v1.GetAccountServiceReply
	(*ListAccountServiceRequest)(nil),   // 8: api.account.service.v1.ListAccountServiceRequest
	(*ListAccountServiceReply)(nil),     // 9: api.account.service.v1.ListAccountServiceReply
}
var file_api_accountService_v1_accountService_proto_depIdxs = []int32{
	0, // 0: api.account.service.v1.AccountService.CreateAccountService:input_type -> api.account.service.v1.CreateAccountServiceRequest
	2, // 1: api.account.service.v1.AccountService.UpdateAccountService:input_type -> api.account.service.v1.UpdateAccountServiceRequest
	4, // 2: api.account.service.v1.AccountService.DeleteAccountService:input_type -> api.account.service.v1.DeleteAccountServiceRequest
	6, // 3: api.account.service.v1.AccountService.GetAccountService:input_type -> api.account.service.v1.GetAccountServiceRequest
	8, // 4: api.account.service.v1.AccountService.ListAccountService:input_type -> api.account.service.v1.ListAccountServiceRequest
	1, // 5: api.account.service.v1.AccountService.CreateAccountService:output_type -> api.account.service.v1.CreateAccountServiceReply
	3, // 6: api.account.service.v1.AccountService.UpdateAccountService:output_type -> api.account.service.v1.UpdateAccountServiceReply
	5, // 7: api.account.service.v1.AccountService.DeleteAccountService:output_type -> api.account.service.v1.DeleteAccountServiceReply
	7, // 8: api.account.service.v1.AccountService.GetAccountService:output_type -> api.account.service.v1.GetAccountServiceReply
	9, // 9: api.account.service.v1.AccountService.ListAccountService:output_type -> api.account.service.v1.ListAccountServiceReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_accountService_v1_accountService_proto_init() }
func file_api_accountService_v1_accountService_proto_init() {
	if File_api_accountService_v1_accountService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_accountService_v1_accountService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccountServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_accountService_v1_accountService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccountServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_accountService_v1_accountService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAccountServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_accountService_v1_accountService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAccountServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_accountService_v1_accountService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAccountServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_accountService_v1_accountService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAccountServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_accountService_v1_accountService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_accountService_v1_accountService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_accountService_v1_accountService_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAccountServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_accountService_v1_accountService_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAccountServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_accountService_v1_accountService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_accountService_v1_accountService_proto_goTypes,
		DependencyIndexes: file_api_accountService_v1_accountService_proto_depIdxs,
		MessageInfos:      file_api_accountService_v1_accountService_proto_msgTypes,
	}.Build()
	File_api_accountService_v1_accountService_proto = out.File
	file_api_accountService_v1_accountService_proto_rawDesc = nil
	file_api_accountService_v1_accountService_proto_goTypes = nil
	file_api_accountService_v1_accountService_proto_depIdxs = nil
}
