// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: api/commentAdmin/v1/commentAdmin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCommentAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateCommentAdminRequest) Reset() {
	*x = CreateCommentAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentAdminRequest) ProtoMessage() {}

func (x *CreateCommentAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_commentAdmin_v1_commentAdmin_proto_rawDescGZIP(), []int{0}
}

type CreateCommentAdminReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateCommentAdminReply) Reset() {
	*x = CreateCommentAdminReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentAdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentAdminReply) ProtoMessage() {}

func (x *CreateCommentAdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentAdminReply.ProtoReflect.Descriptor instead.
func (*CreateCommentAdminReply) Descriptor() ([]byte, []int) {
	return file_api_commentAdmin_v1_commentAdmin_proto_rawDescGZIP(), []int{1}
}

type UpdateCommentAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCommentAdminRequest) Reset() {
	*x = UpdateCommentAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCommentAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentAdminRequest) ProtoMessage() {}

func (x *UpdateCommentAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentAdminRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_commentAdmin_v1_commentAdmin_proto_rawDescGZIP(), []int{2}
}

type UpdateCommentAdminReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCommentAdminReply) Reset() {
	*x = UpdateCommentAdminReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCommentAdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentAdminReply) ProtoMessage() {}

func (x *UpdateCommentAdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentAdminReply.ProtoReflect.Descriptor instead.
func (*UpdateCommentAdminReply) Descriptor() ([]byte, []int) {
	return file_api_commentAdmin_v1_commentAdmin_proto_rawDescGZIP(), []int{3}
}

type DeleteCommentAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCommentAdminRequest) Reset() {
	*x = DeleteCommentAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentAdminRequest) ProtoMessage() {}

func (x *DeleteCommentAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentAdminRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_commentAdmin_v1_commentAdmin_proto_rawDescGZIP(), []int{4}
}

type DeleteCommentAdminReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCommentAdminReply) Reset() {
	*x = DeleteCommentAdminReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentAdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentAdminReply) ProtoMessage() {}

func (x *DeleteCommentAdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentAdminReply.ProtoReflect.Descriptor instead.
func (*DeleteCommentAdminReply) Descriptor() ([]byte, []int) {
	return file_api_commentAdmin_v1_commentAdmin_proto_rawDescGZIP(), []int{5}
}

type GetCommentAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCommentAdminRequest) Reset() {
	*x = GetCommentAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentAdminRequest) ProtoMessage() {}

func (x *GetCommentAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentAdminRequest.ProtoReflect.Descriptor instead.
func (*GetCommentAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_commentAdmin_v1_commentAdmin_proto_rawDescGZIP(), []int{6}
}

type GetCommentAdminReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCommentAdminReply) Reset() {
	*x = GetCommentAdminReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentAdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentAdminReply) ProtoMessage() {}

func (x *GetCommentAdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentAdminReply.ProtoReflect.Descriptor instead.
func (*GetCommentAdminReply) Descriptor() ([]byte, []int) {
	return file_api_commentAdmin_v1_commentAdmin_proto_rawDescGZIP(), []int{7}
}

type ListCommentAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCommentAdminRequest) Reset() {
	*x = ListCommentAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommentAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentAdminRequest) ProtoMessage() {}

func (x *ListCommentAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentAdminRequest.ProtoReflect.Descriptor instead.
func (*ListCommentAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_commentAdmin_v1_commentAdmin_proto_rawDescGZIP(), []int{8}
}

type ListCommentAdminReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCommentAdminReply) Reset() {
	*x = ListCommentAdminReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommentAdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentAdminReply) ProtoMessage() {}

func (x *ListCommentAdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentAdminReply.ProtoReflect.Descriptor instead.
func (*ListCommentAdminReply) Descriptor() ([]byte, []int) {
	return file_api_commentAdmin_v1_commentAdmin_proto_rawDescGZIP(), []int{9}
}

var File_api_commentAdmin_v1_commentAdmin_proto protoreflect.FileDescriptor

var file_api_commentAdmin_v1_commentAdmin_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x1b,
	0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b,
	0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xcd, 0x04, 0x0a,
	0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x74, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x12, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x74, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x74, 0x0a, 0x12, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12,
	0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x6b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6e, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x12, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3c, 0x0a, 0x13,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x23, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x6d,
	0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_commentAdmin_v1_commentAdmin_proto_rawDescOnce sync.Once
	file_api_commentAdmin_v1_commentAdmin_proto_rawDescData = file_api_commentAdmin_v1_commentAdmin_proto_rawDesc
)

func file_api_commentAdmin_v1_commentAdmin_proto_rawDescGZIP() []byte {
	file_api_commentAdmin_v1_commentAdmin_proto_rawDescOnce.Do(func() {
		file_api_commentAdmin_v1_commentAdmin_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_commentAdmin_v1_commentAdmin_proto_rawDescData)
	})
	return file_api_commentAdmin_v1_commentAdmin_proto_rawDescData
}

var file_api_commentAdmin_v1_commentAdmin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_commentAdmin_v1_commentAdmin_proto_goTypes = []interface{}{
	(*CreateCommentAdminRequest)(nil), // 0: api.comment.admin.v1.CreateCommentAdminRequest
	(*CreateCommentAdminReply)(nil),   // 1: api.comment.admin.v1.CreateCommentAdminReply
	(*UpdateCommentAdminRequest)(nil), // 2: api.comment.admin.v1.UpdateCommentAdminRequest
	(*UpdateCommentAdminReply)(nil),   // 3: api.comment.admin.v1.UpdateCommentAdminReply
	(*DeleteCommentAdminRequest)(nil), // 4: api.comment.admin.v1.DeleteCommentAdminRequest
	(*DeleteCommentAdminReply)(nil),   // 5: api.comment.admin.v1.DeleteCommentAdminReply
	(*GetCommentAdminRequest)(nil),    // 6: api.comment.admin.v1.GetCommentAdminRequest
	(*GetCommentAdminReply)(nil),      // 7: api.comment.admin.v1.GetCommentAdminReply
	(*ListCommentAdminRequest)(nil),   // 8: api.comment.admin.v1.ListCommentAdminRequest
	(*ListCommentAdminReply)(nil),     // 9: api.comment.admin.v1.ListCommentAdminReply
}
var file_api_commentAdmin_v1_commentAdmin_proto_depIdxs = []int32{
	0, // 0: api.comment.admin.v1.CommentAdmin.CreateCommentAdmin:input_type -> api.comment.admin.v1.CreateCommentAdminRequest
	2, // 1: api.comment.admin.v1.CommentAdmin.UpdateCommentAdmin:input_type -> api.comment.admin.v1.UpdateCommentAdminRequest
	4, // 2: api.comment.admin.v1.CommentAdmin.DeleteCommentAdmin:input_type -> api.comment.admin.v1.DeleteCommentAdminRequest
	6, // 3: api.comment.admin.v1.CommentAdmin.GetCommentAdmin:input_type -> api.comment.admin.v1.GetCommentAdminRequest
	8, // 4: api.comment.admin.v1.CommentAdmin.ListCommentAdmin:input_type -> api.comment.admin.v1.ListCommentAdminRequest
	1, // 5: api.comment.admin.v1.CommentAdmin.CreateCommentAdmin:output_type -> api.comment.admin.v1.CreateCommentAdminReply
	3, // 6: api.comment.admin.v1.CommentAdmin.UpdateCommentAdmin:output_type -> api.comment.admin.v1.UpdateCommentAdminReply
	5, // 7: api.comment.admin.v1.CommentAdmin.DeleteCommentAdmin:output_type -> api.comment.admin.v1.DeleteCommentAdminReply
	7, // 8: api.comment.admin.v1.CommentAdmin.GetCommentAdmin:output_type -> api.comment.admin.v1.GetCommentAdminReply
	9, // 9: api.comment.admin.v1.CommentAdmin.ListCommentAdmin:output_type -> api.comment.admin.v1.ListCommentAdminReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_commentAdmin_v1_commentAdmin_proto_init() }
func file_api_commentAdmin_v1_commentAdmin_proto_init() {
	if File_api_commentAdmin_v1_commentAdmin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentAdminReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCommentAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCommentAdminReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentAdminReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentAdminReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommentAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_commentAdmin_v1_commentAdmin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommentAdminReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_commentAdmin_v1_commentAdmin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_commentAdmin_v1_commentAdmin_proto_goTypes,
		DependencyIndexes: file_api_commentAdmin_v1_commentAdmin_proto_depIdxs,
		MessageInfos:      file_api_commentAdmin_v1_commentAdmin_proto_msgTypes,
	}.Build()
	File_api_commentAdmin_v1_commentAdmin_proto = out.File
	file_api_commentAdmin_v1_commentAdmin_proto_rawDesc = nil
	file_api_commentAdmin_v1_commentAdmin_proto_goTypes = nil
	file_api_commentAdmin_v1_commentAdmin_proto_depIdxs = nil
}
